#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-DT
Version  : 0.9
Release  : 30
URL      : https://cran.r-project.org/src/contrib/DT_0.9.tar.gz
Source0  : https://cran.r-project.org/src/contrib/DT_0.9.tar.gz
Summary  : A Wrapper of the JavaScript Library 'DataTables'
Group    : Development/Tools
License  : Apache-2.0 GPL-3.0 MIT
Requires: R-crosstalk
Requires: R-htmltools
Requires: R-htmlwidgets
Requires: R-jsonlite
Requires: R-magrittr
Requires: R-promises
BuildRequires : R-crosstalk
BuildRequires : R-htmltools
BuildRequires : R-htmlwidgets
BuildRequires : R-jsonlite
BuildRequires : R-magrittr
BuildRequires : R-promises
BuildRequires : buildreq-R
BuildRequires : util-linux

%description
After you render a table on the page, you can use its output id to access some information about it. Currently the indices of rows on the current page and all pages are available (after filtering is applied). Suppose your output id is `foo`, `input$foo_rows_current` is the indices of rows on the current page, and `input$foo_rows_all` is the indices of rows on all pages.

%prep
%setup -q -c -n DT

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1571820894

%install
export SOURCE_DATE_EPOCH=1571820894
rm -rf %{buildroot}
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library DT
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library DT
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library DT
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc DT || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/DT/DESCRIPTION
/usr/lib64/R/library/DT/INDEX
/usr/lib64/R/library/DT/LICENSE
/usr/lib64/R/library/DT/Meta/Rd.rds
/usr/lib64/R/library/DT/Meta/features.rds
/usr/lib64/R/library/DT/Meta/hsearch.rds
/usr/lib64/R/library/DT/Meta/links.rds
/usr/lib64/R/library/DT/Meta/nsInfo.rds
/usr/lib64/R/library/DT/Meta/package.rds
/usr/lib64/R/library/DT/Meta/vignette.rds
/usr/lib64/R/library/DT/NAMESPACE
/usr/lib64/R/library/DT/NEWS.Rd
/usr/lib64/R/library/DT/R/DT
/usr/lib64/R/library/DT/R/DT.rdb
/usr/lib64/R/library/DT/R/DT.rdx
/usr/lib64/R/library/DT/doc/DT.Rmd
/usr/lib64/R/library/DT/doc/DT.html
/usr/lib64/R/library/DT/doc/index.html
/usr/lib64/R/library/DT/examples/DT-click/DESCRIPTION
/usr/lib64/R/library/DT/examples/DT-click/Readme.md
/usr/lib64/R/library/DT/examples/DT-click/rsconnect/shinyapps.io/yihui/DT-click.dcf
/usr/lib64/R/library/DT/examples/DT-click/server.R
/usr/lib64/R/library/DT/examples/DT-click/ui.R
/usr/lib64/R/library/DT/examples/DT-crosstalk/plotly-persist.R
/usr/lib64/R/library/DT/examples/DT-edit/DESCRIPTION
/usr/lib64/R/library/DT/examples/DT-edit/Readme.md
/usr/lib64/R/library/DT/examples/DT-edit/app.R
/usr/lib64/R/library/DT/examples/DT-edit/rsconnect/shinyapps.io/yihui/DT-edit.dcf
/usr/lib64/R/library/DT/examples/DT-filter/DESCRIPTION
/usr/lib64/R/library/DT/examples/DT-filter/Readme.md
/usr/lib64/R/library/DT/examples/DT-filter/rsconnect/shinyapps.io/yihui/DT-filter.dcf
/usr/lib64/R/library/DT/examples/DT-filter/server.R
/usr/lib64/R/library/DT/examples/DT-filter/ui.R
/usr/lib64/R/library/DT/examples/DT-info/DESCRIPTION
/usr/lib64/R/library/DT/examples/DT-info/Readme.md
/usr/lib64/R/library/DT/examples/DT-info/rsconnect/shinyapps.io/yihui/DT-info.dcf
/usr/lib64/R/library/DT/examples/DT-info/server.R
/usr/lib64/R/library/DT/examples/DT-info/ui.R
/usr/lib64/R/library/DT/examples/DT-proxy/DESCRIPTION
/usr/lib64/R/library/DT/examples/DT-proxy/Readme.md
/usr/lib64/R/library/DT/examples/DT-proxy/rsconnect/shinyapps.io/yihui/DT-proxy.dcf
/usr/lib64/R/library/DT/examples/DT-proxy/server.R
/usr/lib64/R/library/DT/examples/DT-proxy/ui.R
/usr/lib64/R/library/DT/examples/DT-radio/DESCRIPTION
/usr/lib64/R/library/DT/examples/DT-radio/Readme.md
/usr/lib64/R/library/DT/examples/DT-radio/app.R
/usr/lib64/R/library/DT/examples/DT-radio/rsconnect/shinyapps.io/yihui/DT-radio.dcf
/usr/lib64/R/library/DT/examples/DT-reload/app.R
/usr/lib64/R/library/DT/examples/DT-rows/DESCRIPTION
/usr/lib64/R/library/DT/examples/DT-rows/Readme.md
/usr/lib64/R/library/DT/examples/DT-rows/rsconnect/shinyapps.io/yihui/DT-rows.dcf
/usr/lib64/R/library/DT/examples/DT-rows/server.R
/usr/lib64/R/library/DT/examples/DT-rows/ui.R
/usr/lib64/R/library/DT/examples/DT-scroller/DESCRIPTION
/usr/lib64/R/library/DT/examples/DT-scroller/Readme.md
/usr/lib64/R/library/DT/examples/DT-scroller/rsconnect/shinyapps.io/yihui/DT-scroller.dcf
/usr/lib64/R/library/DT/examples/DT-scroller/server.R
/usr/lib64/R/library/DT/examples/DT-scroller/ui.R
/usr/lib64/R/library/DT/examples/DT-scroller/www/large.txt
/usr/lib64/R/library/DT/examples/DT-selection/DESCRIPTION
/usr/lib64/R/library/DT/examples/DT-selection/Readme.md
/usr/lib64/R/library/DT/examples/DT-selection/rsconnect/shinyapps.io/yihui/DT-selection.dcf
/usr/lib64/R/library/DT/examples/DT-selection/server.R
/usr/lib64/R/library/DT/examples/DT-selection/ui.R
/usr/lib64/R/library/DT/examples/DT-shiny/server.R
/usr/lib64/R/library/DT/examples/DT-shiny/ui.R
/usr/lib64/R/library/DT/examples/ajax-shiny.R
/usr/lib64/R/library/DT/examples/datatable.R
/usr/lib64/R/library/DT/help/AnIndex
/usr/lib64/R/library/DT/help/DT.rdb
/usr/lib64/R/library/DT/help/DT.rdx
/usr/lib64/R/library/DT/help/aliases.rds
/usr/lib64/R/library/DT/help/paths.rds
/usr/lib64/R/library/DT/html/00Index.html
/usr/lib64/R/library/DT/html/R.css
/usr/lib64/R/library/DT/htmlwidgets/css/datatables-crosstalk.css
/usr/lib64/R/library/DT/htmlwidgets/datatables.js
/usr/lib64/R/library/DT/htmlwidgets/datatables.yaml
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/AutoFill/css/autoFill.bootstrap.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/AutoFill/css/autoFill.bootstrap4.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/AutoFill/css/autoFill.dataTables.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/AutoFill/css/autoFill.foundation.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/AutoFill/css/autoFill.jqueryui.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/AutoFill/css/autoFill.semanticui.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/AutoFill/js/autoFill.bootstrap.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/AutoFill/js/autoFill.bootstrap4.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/AutoFill/js/autoFill.dataTables.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/AutoFill/js/autoFill.foundation.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/AutoFill/js/autoFill.jqueryui.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/AutoFill/js/autoFill.semanticui.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/AutoFill/js/dataTables.autoFill.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/Buttons/css/buttons.bootstrap.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/Buttons/css/buttons.bootstrap4.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/Buttons/css/buttons.dataTables.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/Buttons/css/buttons.foundation.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/Buttons/css/buttons.jqueryui.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/Buttons/css/buttons.semanticui.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/Buttons/js/buttons.bootstrap.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/Buttons/js/buttons.bootstrap4.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/Buttons/js/buttons.colVis.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/Buttons/js/buttons.dataTables.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/Buttons/js/buttons.flash.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/Buttons/js/buttons.foundation.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/Buttons/js/buttons.html5.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/Buttons/js/buttons.jqueryui.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/Buttons/js/buttons.print.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/Buttons/js/buttons.semanticui.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/Buttons/js/dataTables.buttons.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/Buttons/js/jszip.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/Buttons/js/pdfmake.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/Buttons/js/vfs_fonts.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/Buttons/swf/flashExport.swf
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/ColReorder/css/colReorder.bootstrap.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/ColReorder/css/colReorder.bootstrap4.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/ColReorder/css/colReorder.dataTables.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/ColReorder/css/colReorder.foundation.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/ColReorder/css/colReorder.jqueryui.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/ColReorder/css/colReorder.semanticui.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/ColReorder/js/colReorder.bootstrap.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/ColReorder/js/colReorder.bootstrap4.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/ColReorder/js/colReorder.dataTables.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/ColReorder/js/colReorder.foundation.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/ColReorder/js/colReorder.jqueryui.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/ColReorder/js/colReorder.semanticui.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/ColReorder/js/dataTables.colReorder.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/FixedColumns/css/fixedColumns.bootstrap.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/FixedColumns/css/fixedColumns.bootstrap4.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/FixedColumns/css/fixedColumns.dataTables.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/FixedColumns/css/fixedColumns.foundation.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/FixedColumns/css/fixedColumns.jqueryui.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/FixedColumns/css/fixedColumns.semanticui.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/FixedColumns/js/dataTables.fixedColumns.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/FixedColumns/js/fixedColumns.bootstrap.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/FixedColumns/js/fixedColumns.bootstrap4.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/FixedColumns/js/fixedColumns.dataTables.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/FixedColumns/js/fixedColumns.foundation.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/FixedColumns/js/fixedColumns.jqueryui.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/FixedColumns/js/fixedColumns.semanticui.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/FixedHeader/css/fixedHeader.bootstrap.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/FixedHeader/css/fixedHeader.bootstrap4.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/FixedHeader/css/fixedHeader.dataTables.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/FixedHeader/css/fixedHeader.foundation.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/FixedHeader/css/fixedHeader.jqueryui.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/FixedHeader/css/fixedHeader.semanticui.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/FixedHeader/js/dataTables.fixedHeader.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/FixedHeader/js/fixedHeader.bootstrap.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/FixedHeader/js/fixedHeader.bootstrap4.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/FixedHeader/js/fixedHeader.dataTables.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/FixedHeader/js/fixedHeader.foundation.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/FixedHeader/js/fixedHeader.jqueryui.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/FixedHeader/js/fixedHeader.semanticui.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/KeyTable/css/keyTable.bootstrap.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/KeyTable/css/keyTable.bootstrap4.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/KeyTable/css/keyTable.dataTables.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/KeyTable/css/keyTable.foundation.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/KeyTable/css/keyTable.jqueryui.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/KeyTable/css/keyTable.semanticui.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/KeyTable/js/dataTables.keyTable.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/KeyTable/js/keyTable.bootstrap.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/KeyTable/js/keyTable.bootstrap4.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/KeyTable/js/keyTable.foundation.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/KeyTable/js/keyTable.jqueryui.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/KeyTable/js/keyTable.semanticui.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/Responsive/css/responsive.bootstrap.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/Responsive/css/responsive.bootstrap4.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/Responsive/css/responsive.dataTables.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/Responsive/css/responsive.foundation.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/Responsive/css/responsive.jqueryui.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/Responsive/css/responsive.semanticui.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/Responsive/js/dataTables.responsive.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/Responsive/js/responsive.bootstrap.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/Responsive/js/responsive.bootstrap4.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/Responsive/js/responsive.dataTables.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/Responsive/js/responsive.foundation.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/Responsive/js/responsive.jqueryui.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/Responsive/js/responsive.semanticui.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/RowGroup/css/rowGroup.bootstrap.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/RowGroup/css/rowGroup.bootstrap4.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/RowGroup/css/rowGroup.dataTables.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/RowGroup/css/rowGroup.foundation.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/RowGroup/css/rowGroup.jqueryui.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/RowGroup/css/rowGroup.semanticui.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/RowGroup/js/dataTables.rowGroup.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/RowGroup/js/rowGroup.bootstrap.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/RowGroup/js/rowGroup.bootstrap4.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/RowGroup/js/rowGroup.dataTables.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/RowGroup/js/rowGroup.foundation.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/RowGroup/js/rowGroup.jqueryui.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/RowGroup/js/rowGroup.semanticui.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/RowReorder/css/rowReorder.bootstrap.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/RowReorder/css/rowReorder.bootstrap4.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/RowReorder/css/rowReorder.dataTables.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/RowReorder/css/rowReorder.foundation.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/RowReorder/css/rowReorder.jqueryui.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/RowReorder/css/rowReorder.semanticui.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/RowReorder/js/dataTables.rowReorder.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/RowReorder/js/rowReorder.bootstrap.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/RowReorder/js/rowReorder.bootstrap4.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/RowReorder/js/rowReorder.foundation.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/RowReorder/js/rowReorder.jqueryui.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/RowReorder/js/rowReorder.semanticui.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/Scroller/css/scroller.bootstrap.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/Scroller/css/scroller.bootstrap4.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/Scroller/css/scroller.dataTables.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/Scroller/css/scroller.foundation.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/Scroller/css/scroller.jqueryui.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/Scroller/css/scroller.semanticui.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/Scroller/js/dataTables.scroller.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/Scroller/js/scroller.bootstrap.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/Scroller/js/scroller.bootstrap4.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/Scroller/js/scroller.dataTables.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/Scroller/js/scroller.foundation.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/Scroller/js/scroller.jqueryui.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/Scroller/js/scroller.semanticui.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/Select/css/select.bootstrap.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/Select/css/select.bootstrap4.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/Select/css/select.dataTables.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/Select/css/select.foundation.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/Select/css/select.jqueryui.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/Select/css/select.semanticui.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/Select/js/dataTables.select.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/Select/js/select.bootstrap.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/Select/js/select.bootstrap4.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/Select/js/select.dataTables.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/Select/js/select.foundation.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/Select/js/select.jqueryui.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-extensions/Select/js/select.semanticui.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-plugins/ellipsis/ellipsis.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-plugins/natural/natural.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-plugins/searchHighlight/dataTables.searchHighlight.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-plugins/searchHighlight/dataTables.searchHighlight.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables-plugins/searchHighlight/jquery.highlight.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables/css/dataTables.bootstrap.extra.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables/css/dataTables.bootstrap.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables/css/dataTables.bootstrap4.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables/css/dataTables.foundation.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables/css/dataTables.jqueryui.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables/css/dataTables.material.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables/css/dataTables.semanticui.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables/css/dataTables.uikit.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables/css/jquery.dataTables.extra.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables/css/jquery.dataTables.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables/js/dataTables.bootstrap.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables/js/dataTables.bootstrap4.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables/js/dataTables.dataTables.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables/js/dataTables.foundation.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables/js/dataTables.jqueryui.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables/js/dataTables.material.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables/js/dataTables.semanticui.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables/js/dataTables.uikit.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables/js/jquery.dataTables.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/datatables/license.txt
/usr/lib64/R/library/DT/htmlwidgets/lib/jquery/LICENSE.txt
/usr/lib64/R/library/DT/htmlwidgets/lib/jquery/jquery.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/nouislider/jquery.nouislider.min.css
/usr/lib64/R/library/DT/htmlwidgets/lib/nouislider/jquery.nouislider.min.js
/usr/lib64/R/library/DT/htmlwidgets/lib/selectize/selectize.bootstrap3.css
/usr/lib64/R/library/DT/htmlwidgets/lib/selectize/selectize.min.js
